#ifndef KANOOPTORRENT_H
#define KANOOPTORRENT_H
#include <Qt>

#ifdef KANOOP_TORRENT_LIBRARY
#define LIBKANOOPTORRENT_EXPORT Q_DECL_EXPORT
#else
#define LIBKANOOPTORRENT_EXPORT Q_DECL_IMPORT
#endif

#endif // KANOOPTORRENT_H
